# This is a basic workflow to help you get started with Actions

name: Firebase
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up nodejs
      uses: actions/setup-node@v1.4.2
    - name: Install deps
      run: npm ci
    - name: Build
      run: npm run build
    - name: deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: npx firebase deploy --token "$FIREBASE_TOKEN"
